INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Departments', 'Xem danh sách đơn vị/phòng ban', 'view_departments');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Manage Departments', 'Quản lý đơn vị/phòng ban', 'manage_departments');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Rooms', 'Xem danh sách phòng học/phòng làm việc', 'view_rooms');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Manage Rooms', 'Quản lý phòng học/phòng làm việc', 'manage_rooms');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Employees', 'Xem danh sách cán bộ', 'view_employees');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Manage Employees', 'Quản lý thông tin cán bộ', 'manage_employees');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Equipment', 'Xem danh sách thiết bị', 'view_equipment');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Manage Equipment', 'Quản lý thiết bị', 'manage_equipment');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Equipment Group', 'Xem nhóm thiết bị', 'view_equipment_group');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Manage Equipment Group', 'Quản lý nhóm thiết bị', 'manage_equipment_group');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Suppliers', 'Xem nhà cung cấp', 'view_suppliers');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Manage Suppliers', 'Quản lý nhà cung cấp', 'manage_suppliers');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Manufacturers', 'Xem nhà sản xuất', 'view_manufacturers');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Manage Manufacturers', 'Quản lý nhà sản xuất', 'manage_manufacturers');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Units', 'Xem đơn vị tính', 'view_units');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Manage Units', 'Quản lý đơn vị tính', 'manage_units');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Import Receipts All', 'Xem tất cả phiếu nhập', 'view_import_receipts_all');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Import Receipts Own', 'Xem phiếu nhập do mình tạo', 'view_import_receipts_own');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Create Import Receipts', 'Tạo phiếu nhập', 'create_import_receipts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Approve Import Receipts', 'Duyệt phiếu nhập', 'approve_import_receipts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Reject Import Receipts', 'Từ chối phiếu nhập', 'reject_import_receipts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Export Receipts All', 'Xem tất cả phiếu xuất', 'view_export_receipts_all');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Export Receipts Own', 'Xem phiếu xuất do mình tạo', 'view_export_receipts_own');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Create Export Receipts', 'Tạo phiếu xuất', 'create_export_receipts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Approve Export Receipts', 'Duyệt phiếu xuất', 'approve_export_receipts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Transfer Receipts All', 'Xem tất cả phiếu điều chuyển', 'view_transfer_receipts_all');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Transfer Receipts Own', 'Xem phiếu điều chuyển do mình tạo', 'view_transfer_receipts_own');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Create Transfer Receipts', 'Tạo phiếu điều chuyển', 'create_transfer_receipts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Approve Transfer Receipts', 'Duyệt phiếu điều chuyển', 'approve_transfer_receipts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Borrow Receipts All', 'Xem tất cả phiếu mượn', 'view_borrow_receipts_all');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Borrow Receipts Own', 'Xem phiếu mượn do mình tạo', 'view_borrow_receipts_own');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Create Borrow Receipts', 'Tạo phiếu mượn', 'create_borrow_receipts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Approve Borrow Receipts', 'Duyệt phiếu mượn', 'approve_borrow_receipts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Return Borrowed Equipment', 'Trả thiết bị đã mượn', 'return_borrowed_equipment');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Liquidation Receipts All', 'Xem tất cả phiếu thanh lý', 'view_liquidation_receipts_all');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Liquidation Receipts Own', 'Xem phiếu thanh lý do mình tạo', 'view_liquidation_receipts_own');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Create Liquidation Receipts', 'Tạo phiếu thanh lý', 'create_liquidation_receipts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Approve Liquidation Receipts', 'Duyệt phiếu thanh lý', 'approve_liquidation_receipts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Accounts', 'Xem danh sách tài khoản', 'view_accounts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Manage Accounts', 'Quản lý tài khoản', 'manage_accounts');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Roles', 'Xem danh sách vai trò', 'view_roles');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Manage Roles', 'Quản lý vai trò', 'manage_roles');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Assign Roles', 'Gán quyền cho tài khoản', 'assign_roles');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Equipment Statistics', 'Xem thống kê thiết bị', 'view_equipment_statistics');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Room Usage Statistics', 'Xem thống kê sử dụng phòng', 'view_room_usage_statistics');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Cost Statistics', 'Xem thống kê chi phí', 'view_cost_statistics');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Export Reports', 'Xuất báo cáo', 'export_reports');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Notifications', 'Xem thông báo', 'view_notifications');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('Manage Notifications', 'Quản lý thông báo', 'manage_notifications');
INSERT INTO tb_permission (permission_name, permission_description, slug) VALUES ('View Logs', 'Xem nhật ký hệ thống', 'view_logs');